language: android
android:
  components:
    - build-tools-20.0.0
    - android-19
env:
  - CORDOVA_VERSION=4.0.0 NODE_VERSION=0.10 WEBAPP_VERSION=0.5.1
  - CORDOVA_VERSION=4.1.2 NODE_VERSION=0.10 WEBAPP_VERSION=0.5.1
  - CORDOVA_VERSION=4.2.0 NODE_VERSION=0.10 WEBAPP_VERSION=0.5.1
  - CORDOVA_VERSION=4.3.0 NODE_VERSION=0.10 WEBAPP_VERSION=0.5.1
  - CORDOVA_VERSION=4.0.0 NODE_VERSION=0.12 WEBAPP_VERSION=0.5.1
  - CORDOVA_VERSION=4.1.2 NODE_VERSION=0.12 WEBAPP_VERSION=0.5.1
  - CORDOVA_VERSION=4.2.0 NODE_VERSION=0.12 WEBAPP_VERSION=0.5.1
  - CORDOVA_VERSION=4.3.0 NODE_VERSION=0.12 WEBAPP_VERSION=0.5.1
before_install:
  - nvm install $NODE_VERSION && nvm use $NODE_VERSION
  - npm update -g npm
  - npm install -g grunt-cli generator-webapp@$WEBAPP_VERSION cordova@$CORDOVA_VERSION
  - node --version
  - npm --version
  - cordova --version
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-graybullet-cordova' ]; then cd .. && eval "mv $currentfolder generator-graybullet-cordova" && cd generator-graybullet-cordova; fi
  - npm install
  - npm install generator-webapp@$WEBAPP_VERSION
script:
  - npm test
