language: android
android:
  components:
    - build-tools-20.0.0
    - android-19
env:
  - CORDOVA_VERSION=4.0.0 NODE_VERSION=0.10
  - CORDOVA_VERSION=4.1.2 NODE_VERSION=0.10
  - CORDOVA_VERSION=4.2.0 NODE_VERSION=0.10
  - CORDOVA_VERSION=4.0.0 NODE_VERSION=0.11
  - CORDOVA_VERSION=4.1.2 NODE_VERSION=0.11
  - CORDOVA_VERSION=4.2.0 NODE_VERSION=0.11
before_install:
  - nvm instal $NODE_VERSION && nvm use $NODE_VERSION
  - npm install -g grunt-cli generator-webapp@0.5.1 cordova@$CORDOVA_VERSION
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-graybullet-cordova' ]; then cd .. && eval "mv $currentfolder generator-graybullet-cordova" && cd generator-graybullet-cordova; fi
  - npm install
script:
  - npm test
