language: android
android:
  components:
    - build-tools-20.0.0
    - android-19
env:
  - CORDOVA_VERSION=4.0.0 NODE_VERSION=0.12 NPM_VERSION=lts WEBAPP_VERSION=0.5.1
  - CORDOVA_VERSION=4.1.2 NODE_VERSION=0.12 NPM_VERSION=lts WEBAPP_VERSION=0.5.1
  - CORDOVA_VERSION=4.2.0 NODE_VERSION=0.12 NPM_VERSION=lts WEBAPP_VERSION=0.5.1
  - CORDOVA_VERSION=4.3.1 NODE_VERSION=0.12 NPM_VERSION=lts WEBAPP_VERSION=0.5.1
  - CORDOVA_VERSION=5.0.0 NODE_VERSION=0.12 NPM_VERSION=lts WEBAPP_VERSION=0.5.1
  - CORDOVA_VERSION=5.1.1 NODE_VERSION=0.12 NPM_VERSION=lts WEBAPP_VERSION=0.5.1
  - CORDOVA_VERSION=5.2.0 NODE_VERSION=0.12 NPM_VERSION=lts WEBAPP_VERSION=0.5.1
  - CORDOVA_VERSION=5.3.3 NODE_VERSION=0.12 NPM_VERSION=lts WEBAPP_VERSION=0.5.1
  - CORDOVA_VERSION=5.0.0 NODE_VERSION=4 NPM_VERSION=lts WEBAPP_VERSION=0.5.1
  - CORDOVA_VERSION=5.1.1 NODE_VERSION=4 NPM_VERSION=lts WEBAPP_VERSION=0.5.1
  - CORDOVA_VERSION=5.2.0 NODE_VERSION=4 NPM_VERSION=lts WEBAPP_VERSION=0.5.1
  - CORDOVA_VERSION=5.3.3 NODE_VERSION=4 NPM_VERSION=lts WEBAPP_VERSION=0.5.1
  - CORDOVA_VERSION=5.0.0 NODE_VERSION=4 NPM_VERSION=lts WEBAPP_VERSION=1.1.0
  - CORDOVA_VERSION=5.1.1 NODE_VERSION=4 NPM_VERSION=lts WEBAPP_VERSION=1.1.0
  - CORDOVA_VERSION=5.2.0 NODE_VERSION=4 NPM_VERSION=lts WEBAPP_VERSION=1.1.0
  - CORDOVA_VERSION=5.3.3 NODE_VERSION=4 NPM_VERSION=lts WEBAPP_VERSION=1.1.0
  - CORDOVA_VERSION=5.4.1 NODE_VERSION=5 NPM_VERSION=latest WEBAPP_VERSION=1.1.0
before_install:
  - nvm install $NODE_VERSION && nvm use $NODE_VERSION
  - npm install -g npm@$NPM_VERSION
  - npm install -g grunt-cli
  - npm install -g generator-webapp@$WEBAPP_VERSION
  - npm install -g cordova@$CORDOVA_VERSION
  - ln -s $NVM_BIN/../lib/node_modules/generator-webapp ..
  - node --version
  - npm --version
  - cordova --version
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-graybullet-cordova' ]; then cd .. && eval "mv $currentfolder generator-graybullet-cordova" && cd generator-graybullet-cordova; fi
  - npm install
  - npm install generator-webapp@$WEBAPP_VERSION
script:
  - npm test
